# Site settings
title: Chile trip photo report
description: > # this means to ignore newlines until "baseurl:"
    Some images from my trip to Chile in January 2016.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chile.outoftheblue.pl" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
